development:
  adapter: mysql2
  database: my_money
  username: root
  password: 1993
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: my_money_test
  username: root
  password: 1993
  host: localhost
  pool: 5
  timeout: 5000
